import type { AllowedBins, AllowedProfiles } from '../agent/tools/exec/policy';

export const profiles = {
  coreutils_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-a': { takesValue: false },
      '-A': { takesValue: false },
      '-h': { takesValue: false },
      '-l': { takesValue: false },
      '-R': { takesValue: false },
      '-s': { takesValue: false },
      '-b': { takesValue: false },
      '-i': { takesValue: false },
      '-n': {
        takesValue: true,
        value: { type: 'int', min: 0, max: 5000 },
      },
    },
  },
  git_read: {
    allowSubcommands: [
      ['status'],
      ['diff'],
      ['log'],
      ['branch'],
      ['rev-parse'],
      ['show'],
    ],
    denyFlags: [],
    allowFlags: {
      '--no-pager': { takesValue: false },
      '--oneline': { takesValue: false },
      '--decorate': { takesValue: false },
      '--graph': { takesValue: false },
      '-s': { takesValue: false },
      '-b': { takesValue: false },
      '-u': { takesValue: false },
      '-n': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 200 },
      },
    },
  },
  head_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-n': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 1000 },
      },
      '--lines': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 1000 },
      },
    },
  },
  tail_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-n': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 1000 },
      },
      '--lines': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 1000 },
      },
    },
  },
  rg_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-n': { takesValue: false },
      '-i': { takesValue: false },
      '-S': { takesValue: false },
      '-U': { takesValue: false },
      '-g': { takesValue: true, value: { type: 'path' } },
      '--glob': { takesValue: true, value: { type: 'path' } },
      '--type': { takesValue: true, value: { type: 'path' } },
      '--files': { takesValue: false },
      '--line-number': { takesValue: false },
      '--context': {
        takesValue: true,
        value: { type: 'int', min: 0, max: 50 },
      },
    },
  },
  cat_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {},
  },
  ls_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-a': { takesValue: false },
      '-l': { takesValue: false },
      '-h': { takesValue: false },
      '-R': { takesValue: false },
      '--all': { takesValue: false },
      '--long': { takesValue: false },
    },
  },
  greg_read: {
    allowSubcommands: [
      ['logs'],
      ['gateway'],
      ['heartbeat'],
      ['doctor'],
      ['config'],
      ['sessions'],
      ['skills'],
      ['telegram', 'send'],
      ['hub', 'notion', '*'],
      ['hub', 'strava', '*'],
    ],
    denyFlags: [],
    allowFlags: {
      '--help': { takesValue: false },
      '-h': { takesValue: false },
      '-v': { takesValue: false },
      '--verbose': { takesValue: false },
      '--voice': { takesValue: false },
      '--json': { takesValue: false },
      '-n': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 200 },
      },
    },
  },
  gog_read: {
    allowSubcommands: [
      ['calendar', 'calendars'],
      ['calendar', 'events'],
      ['calendar', 'event'],
      ['calendar', 'get'],
      ['calendar', 'search'],
      ['calendar', 'freebusy'],
      ['calendar', 'conflicts'],
      ['calendar', 'team'],
      ['calendar', 'colors'],
      ['calendar', 'users'],
      ['calendar', 'time'],
      ['tasks', 'lists'],
      ['tasks', 'list'],
      ['tasks', 'get'],
      ['time'],
      ['gmail', 'search'],
      ['gmail', 'messages', 'search'],
      ['gmail', 'thread', 'get'],
      ['gmail', 'get'],
      ['gmail', 'url'],
      ['gmail', 'attachment'],
      ['gmail', 'labels', 'list'],
      ['gmail', 'labels', 'get'],
      ['gmail', 'drafts', 'list'],
      ['gmail', 'history'],
      ['contacts', 'list'],
      ['contacts', 'search'],
      ['contacts', 'get'],
      ['contacts', 'other'],
      ['contacts', 'directory'],
      ['people'],
      ['drive', 'ls'],
      ['drive', 'search'],
      ['drive', 'get'],
      ['drive', 'url'],
      ['drive', 'download'],
      ['drive', 'drives'],
      ['docs', 'info'],
      ['docs', 'cat'],
      ['docs', 'export'],
      ['docs', 'list-tabs'],
      ['sheets', 'metadata'],
      ['sheets', 'get'],
      ['sheets', 'export'],
      ['sheets', 'named-ranges'],
      ['sheets', 'notes'],
      ['sheets', 'links'],
      ['sheets', 'read-format'],
      ['slides', 'info'],
      ['slides', 'list-slides'],
      ['slides', 'export'],
      ['forms', 'get'],
      ['forms', 'responses'],
      ['groups', 'list'],
      ['groups', 'members'],
      ['auth', 'list'],
      ['auth', 'status'],
    ],
    denyFlags: [],
    allowFlags: {
      '--help': { takesValue: false },
      '-h': { takesValue: false },
      '-v': { takesValue: false },
      '--verbose': { takesValue: false },
      '--json': { takesValue: false },
      '--plain': { takesValue: false },
      '--no-input': { takesValue: false },
      '--include-body': { takesValue: false },
      '--download': { takesValue: false },
      '--today': { takesValue: false },
      '--tomorrow': { takesValue: false },
      '--week': { takesValue: false },
      '--all': { takesValue: false },
      '--all-tabs': { takesValue: false },
      '--check': { takesValue: false },
      '--freebusy': { takesValue: false },
      '--weekday': { takesValue: false },
      '--effective': { takesValue: false },
      '--max': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 500 },
      },
      '--days': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 365 },
      },
      '--account': { takesValue: true },
      '--from': { takesValue: true },
      '--to': { takesValue: true },
      '--format': { takesValue: true },
      '--out': { takesValue: true, value: { type: 'path' } },
      '--out-dir': { takesValue: true, value: { type: 'path' } },
      '--tab': { takesValue: true },
      '--tab-id': { takesValue: true },
      '--timezone': { takesValue: true },
      '--calendars': { takesValue: true },
      '--cal': { takesValue: true },
      '--query': { takesValue: true },
      '--max-bytes': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 100000 },
      },
    },
  },
  gog_write: {
    allowSubcommands: [
      ['calendar', 'create'],
      ['calendar', 'update'],
      ['calendar', 'delete'],
      ['calendar', 'respond'],
      ['tasks', 'lists', 'create'],
      ['tasks', 'add'],
      ['tasks', 'update'],
      ['tasks', 'done'],
      ['tasks', 'undo'],
      ['tasks', 'delete'],
      ['gmail', 'drafts', 'create'],
      ['gmail', 'drafts', 'update'],
      ['gmail', 'drafts', 'send'],
      ['gmail', 'drafts', 'delete'],
      ['gmail', 'thread', 'modify'],
      ['gmail', 'labels', 'create'],
      ['contacts', 'create'],
      ['contacts', 'update'],
    ],
    denyFlags: [
      // blocks permanent deletion
      '--permanent',
    ],
    allowFlags: {
      '--help': { takesValue: false },
      '-h': { takesValue: false },
      '--json': { takesValue: false },
      '--force': { takesValue: false },
      '--no-input': { takesValue: false },
      '--all-day': { takesValue: false },
      '--quote': { takesValue: false },
      '--track': { takesValue: false },
      '--account': { takesValue: true },
      '--summary': { takesValue: true },
      '--from': { takesValue: true },
      '--to': { takesValue: true },
      '--subject': { takesValue: true },
      '--body': { takesValue: true },
      '--body-html': { takesValue: true },
      '--body-file': { takesValue: true, value: { type: 'path' } },
      '--location': { takesValue: true },
      '--attendees': { takesValue: true },
      '--add-attendee': { takesValue: true },
      '--send-updates': { takesValue: true },
      '--status': { takesValue: true },
      '--title': { takesValue: true },
      '--due': { takesValue: true },
      '--repeat': { takesValue: true },
      '--repeat-count': {
        takesValue: true,
        value: { type: 'int', min: 1, max: 52 },
      },
      '--rrule': { takesValue: true },
      '--add': { takesValue: true },
      '--remove': { takesValue: true },
      '--given': { takesValue: true },
      '--family': { takesValue: true },
      '--email': { takesValue: true },
      '--phone': { takesValue: true },
      '--address': { takesValue: true },
      '--notes': { takesValue: true },
      '--reply-to-message-id': { takesValue: true },
      '--reminder': { takesValue: true },
      '--description': { takesValue: true },
      '--event-type': { takesValue: true },
      '--timezone': { takesValue: true },
    },
  },
  jq_read: {
    allowSubcommands: 'all',
    denyFlags: [],
    allowFlags: {
      '-r': { takesValue: false },
      '-e': { takesValue: false },
      '-c': { takesValue: false },
      '-S': { takesValue: false },
      '-s': { takesValue: false },
      '--raw-output': { takesValue: false },
      '--exit-status': { takesValue: false },
      '--compact-output': { takesValue: false },
      '--sort-keys': { takesValue: false },
      '--slurp': { takesValue: false },
    },
  },
} satisfies AllowedProfiles;

export const readOnly: AllowedBins = {
  '/usr/bin/wc': { profiles: ['coreutils_read'] },
  '/usr/bin/uniq': { profiles: ['coreutils_read'] },
  '/usr/bin/grep': { profiles: ['coreutils_read'] },
  '/usr/bin/file': { profiles: ['coreutils_read'] },
  '/usr/bin/stat': { profiles: ['coreutils_read'] },
  '/usr/bin/readlink': { profiles: ['coreutils_read'] },
  '/usr/bin/whoami': { profiles: ['coreutils_read'] },
  '/usr/bin/id': { profiles: ['coreutils_read'] },
  '/usr/bin/env': { profiles: ['coreutils_read'] },
  '/bin/date': { profiles: ['coreutils_read'] },
  '/bin/hostname': { profiles: ['coreutils_read'] },
  '/usr/bin/uname': { profiles: ['coreutils_read'] },
  '/usr/bin/diff': { profiles: ['coreutils_read'] },
  '/usr/bin/cut': { profiles: ['coreutils_read'] },
  '/usr/bin/tr': { profiles: ['coreutils_read'] },
  '/usr/bin/nl': { profiles: ['coreutils_read'] },
  '/usr/bin/seq': { profiles: ['coreutils_read'] },
  '/usr/bin/du': { profiles: ['coreutils_read'] },
  '/bin/df': { profiles: ['coreutils_read'] },
  '/usr/bin/sort': { profiles: ['coreutils_read'] },
  '/usr/bin/sed': { profiles: ['coreutils_read'] },
  '/usr/bin/awk': { profiles: ['coreutils_read'] },
  '/usr/bin/xargs': { profiles: ['coreutils_read'] },
  '/usr/bin/comm': { profiles: ['coreutils_read'] },
  '/usr/bin/paste': { profiles: ['coreutils_read'] },

  '/usr/bin/jq': { profiles: ['jq_read'] },
  '/usr/bin/git': { profiles: ['git_read'] },
  '/usr/bin/head': { profiles: ['head_read'] },
  '/usr/bin/tail': { profiles: ['tail_read'] },
  '/bin/cat': { profiles: ['cat_read'] },
  '/bin/ls': { profiles: ['ls_read'] },
  '/opt/homebrew/bin/gog': { profiles: ['gog_read'] },

  '~/.bun/bin/greg': { profiles: ['greg_read'] },
};

export const safeWrite: AllowedBins = {
  '/opt/homebrew/bin/gog': { profiles: ['gog_write'] },
};
